apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: ovpn
data:
  .dockerconfigjson: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
type: kubernetes.io/dockerconfigjson