kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ovpn0-pvc
  namespace: ovpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "standard"